name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  go-fmt:
    name: go fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Format Go
        run: | 
          result=$(gofmt -l .)
          if [ -n $result ]; then
            exit 1
          fi

  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      - name: Format terraform
        working-directory: ./terraform
        run: terraform fmt -recursive -check
