name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  go-fmt:
    name: go fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Format Go
        run: | 
          result=$(gofmt -l . | wc -l)
          if [ $result -ne 0 ]; then
            exit 1
          fi

  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: [ '1.1.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}
      - name: Format terraform
        working-directory: ./terraform
        run: terraform fmt -recursive -check
      - name: Validate terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
