name: run benchmark

on:
  issue_comment:
    types:
      - created

jobs:
  run-bench:
    # add comment of pull request && comment is KEYWORD
    if: (github.event.issue.pull_request != null) && (contains(github.event.comment.body, '/bench'))
    runs-on: ubuntu-latest

    outputs:
      bench-result: ${{ steps.bench.outputs.result }}
      webapp1-result: ${{ steps.webapp1.outputs.result }}
      webapp2-result: ${{ steps.webapp2.outputs.result }}
      webapp3-result: ${{ steps.webapp3.outputs.result }}

    steps:
      - name: Get PR's branch
        uses: actions/github-script@v2
        id: get-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-target-branch.outputs.result }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Add ssh key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Apply terraform
        id: apply-terraform
        working-directory: ./terraform
        run: |
          echo 'allow_ssh_cidr = "0.0.0.0/0"' > terraform.tfvars
          terraform init
          terraform validate
          terraform apply -auto-approve

          bench_ip=$(cat terraform.tfstate | jq .outputs.bench_public_ip.value | tr -d '"')
          webapp1_ip=$(cat terraform.tfstate | jq .outputs.webapp1_public_ip.value | tr -d '"')
          webapp2_ip=$(cat terraform.tfstate | jq .outputs.webapp2_public_ip.value | tr -d '"')
          webapp3_ip=$(cat terraform.tfstate | jq .outputs.webapp3_public_ip.value | tr -d '"')
          echo "::add-mask::$bench_ip"
          echo "::add-mask::$webapp1_ip"
          echo "::add-mask::$webapp2_ip"
          echo "::add-mask::$webapp3_ip"
          echo "::set-output name=bench_ip::$bench_ip"
          echo "::set-output name=webapp1_ip::$webapp1_ip"
          echo "::set-output name=webapp2_ip::$webapp2_ip"
          echo "::set-output name=webapp3_ip::$webapp3_ip"

      # instanceを立てた直後はuser_dataのスクリプト実行が完了していない可能性があるので，adhocにsshの疎通確認をする
      - name: Check ssh
        run: |
          bench_ip=${{ steps.apply-terraform.outputs.bench_ip }}
          webapp1_ip=${{ steps.apply-terraform.outputs.webapp1_ip }}
          webapp2_ip=${{ steps.apply-terraform.outputs.webapp2_ip }}
          webapp3_ip=${{ steps.apply-terraform.outputs.webapp3_ip }}
          for ip in $bench_ip $webapp1_ip $webapp2_ip $webapp3_ip; do
            for i in `seq 10`; do
              echo $i
              ssh isucon@$ip -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -- : | result=$?
              if [ "$result" = 0 ]; then
                break
              else
                echo $result
              fi
              sleep 3
            done
          done

      - name: Run bench
        id: bench
        run: |
          ssh isucon@${{ steps.apply-terraform.outputs.bench_ip }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./webapp/script/run-bench.sh > bench_result.txt

          bench_result=$(cat bench_result.txt)
          bench_result=${bench_result//$'\n'/\\n}
          bench_result=${bench_result//$'"'/'\"'}
          echo "::set-output name=result::$bench_result"

      - name: Get metrics of webapp1
        id: webapp1
        run: |
          ssh isucon@${{ steps.apply-terraform.outputs.webapp1_ip }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./webapp/script/alp.sh > webapp1_result.txt
          
          webapp1_result=$(cat webapp1_result.txt)
          webapp1_result=${webapp1_result//$'\n'/\\n}
          webapp1_result=${webapp1_result//$'"'/'\"'}
          echo "::set-output name=result::$webapp1_result"

      - name: Get metrics of webapp2
        id: webapp2
        run: |
          ssh isucon@${{ steps.apply-terraform.outputs.webapp2_ip }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./webapp/script/slow_query.sh > webapp2_result.txt
          
          webapp2_result=$(cat webapp2_result.txt)
          webapp2_result=${webapp2_result//$'\n'/\\n}
          webapp2_result=${webapp2_result//$'"'/'\"'}
          echo "::set-output name=result::$webapp2_result"

      - name: Get metrics of webapp3
        id: webapp3
        run: |
          ssh isucon@${{ steps.apply-terraform.outputs.webapp3_ip }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./webapp/script/alp.sh > webapp3_result.txt
          
          webapp3_result=$(cat webapp3_result.txt)
          webapp3_result=${webapp3_result//$'\n'/\\n}
          webapp3_result=${webapp3_result//$'"'/'\"'}
          echo "::set-output name=result::$webapp3_result"

      - name: Destroy terraform
        if: always()
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve

  comment-results:
    runs-on: ubuntu-latest
    needs: run-bench
    if: always()
    steps:
      - name: Get commit
        uses: actions/github-script@v2
        id: get-target-commit
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.sha

      - name: Build result comment
        id: comment
        run: |
          comment="
          # Benchmark Result
          ## Target Commit
          https://github.com/${{ github.repository }}/commit/${{ steps.get-target-commit.outputs.result }}
          ## Result
          ### Benchmark
          <details>

          ```
          ${{ needs.run-bench.outputs.bench-result }}
          ```

          </details>

          ### Alp of webapp1
          <details>

          ```
          ${{ needs.run-bench.outputs.webapp1-result }}
          ```

          </details>

          ### Slow query of webapp2
          <details>

          ```
          ${{ needs.run-bench.outputs.webapp2-result }}
          ```
          
          </details>

          ### Alp of webapp3
          <details>

          ```
          ${{ needs.run-bench.outputs.webapp3-result }}
          ```
          
          </details>
          
          "
          
          comment="${comment//$'\n'/\\n}"
          echo "::set-output name=comment::$comment"

      - name: Comment results
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.comment.outputs.comment }}`
            })
