name: run benchmark

on:
  issue_comment:
    types:
      - created

jobs:
  run-bench:
    # add comment of pull request && comment is KEYWORD
    if: (github.event.issue.pull_request != null) && github.event.comment.body == '/bench'
    runs-on: ubuntu-latest

    steps:
      # コメントが付けられたPRのブランチを取得
      - uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
      # git checkout
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
      # branch名をコメントする
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `This branch is ${steps.set-target-branch.outputs.result}`
            })
